### ISSUE TITLE
Select element is inconsistent across browsers

### ISSUE THREAD

**Issue by terotik** [City-of-Helsinki/hel-bootstrap-3#6]
Chrome (OSX):
<img width="504" alt="screen shot 2017-06-12 at 11 08 25" src="https://user-images.githubusercontent.com/664877/27024515-899aca56-4f5f-11e7-9656-ba44e6bc4269.png">
Safari (OSX):
<img width="503" alt="screen shot 2017-06-12 at 11 07 46" src="https://user-images.githubusercontent.com/664877/27024517-89c1851a-4f5f-11e7-90b9-aabc0c542a78.png">
Firefox (OSX):
<img width="504" alt="screen shot 2017-06-12 at 11 07 37" src="https://user-images.githubusercontent.com/664877/27024516-89c17052-4f5f-11e7-8c94-c8195a7ff3a3.png">
IE11 (Win7):
![screen shot 2017-06-12 at 11 14 10](https://user-images.githubusercontent.com/664877/27024717-67603452-4f60-11e7-8021-3e3b86cb0b38.png)

**Comment by terotik** [comment]
Fixed on 8449480d7655d37e1fb53d7da1723408a6fc1505

Requires extra wrapper with ``.select``-class

**Comment by terotik** [comment]
This could work:
```SCSS
select.form-control {
    -webkit-appearance: none;
    -webkit-border-radius: 0px;
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E%3Cstyle%3E.st0%7Bfill:%23abb2bd%7D%3C/style%3E%3Cpath class='st0' d='M7.4 8h9.2L12 16z'/%3E%3C/svg%3E");
    background-position: 100% 50%;
    background-repeat: no-repeat;
}
```

(needs browser testing first)
